# Travis CI config to run tests using Docker
# See: https://docs.travis-ci.com/user/docker/
# See: https://docker.io/
sudo: required
dist: trusty
language: c  # C seems to have the least amount of setup
services:
  - docker

language:
  - python
python:
  - "2.7"

before_install:
  - docker version
  - export DOCKER_IMAGE=hazyresearch/snorkel-dev
  - docker pull $DOCKER_IMAGE

  # rescue git from detached HEAD state for DockerBuild
  - if [[ $TRAVIS_PULL_REQUEST = false ]];
    then git checkout -qf $TRAVIS_BRANCH;
    else git checkout -qf -b pr$TRAVIS_PULL_REQUEST;
    fi

install:
  - ./DockerBuild/build-in-container

script:
  - ./DockerBuild/test-in-container

after_script:
  - docker login -e "$encrypted_DOCKER_EMAIL" -u "$encrypted_DOCKER_USERNAME" -p "$encrypted_DOCKER_PASSWORD";

    # decide what tag to use
  - if [[ $TRAVIS_TEST_RESULT = 0 ]];
    then verdict=PASS;
    else verdict=FAIL;
    fi;
    branchTag=$(echo -n "$TRAVIS_BRANCH" | tr -c 'A-Za-z0-9_.-' _);

    # push the test result
  - if [[ $TRAVIS_PULL_REQUEST = false ]];
    then docker tag $DOCKER_IMAGE:latest-test  $DOCKER_IMAGE:$branchTag.latest-test;
         docker push                           $DOCKER_IMAGE:$branchTag.latest-test;
         docker tag $DOCKER_IMAGE:latest-test  $DOCKER_IMAGE:$branchTag.latest-test-$verdict;
         docker push                           $DOCKER_IMAGE:$branchTag.latest-test-$verdict;
    else docker tag $DOCKER_IMAGE:latest-test  $DOCKER_IMAGE:pr$TRAVIS_PULL_REQUEST-test;
         docker push                           $DOCKER_IMAGE:pr$TRAVIS_PULL_REQUEST-test;
    fi;

    # update the master image with the successful build
  - case $TRAVIS_EVENT_TYPE-$TRAVIS_BRANCH-$verdict in
        push-master-PASS)
            docker tag $DOCKER_IMAGE:latest-build $DOCKER_IMAGE:latest;
            docker push                           $DOCKER_IMAGE:latest;;
        push-*-PASS)
            docker tag $DOCKER_IMAGE:latest-build $DOCKER_IMAGE:$branchTag.latest;
            docker push                           $DOCKER_IMAGE:$branchTag.latest;
    esac;

