# Only run CI on master, release branches, tags, and PRs
if: tag IS present OR type = pull_request OR ((branch = master OR branch = redux OR branch =~ release-*) AND type = push)

# Main dist is Python
language: python

# Cache package wheels
cache: pip

# python3.7 only available on xenial
dist: xenial

jobs:
  include:
    - if: type = pull_request
      name: "Python 3.6: unit tests"
      python: 3.6
      env: TOXENV=coverage,doctest,type,check TOX_INSTALL_DIR=.env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - if: type = pull_request
      name: "Python 3.7: unit tests"
      python: 3.7
      env: TOXENV=coverage,doctest,type,check TOX_INSTALL_DIR=.env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - if: type != pull_request
      name: "Python 3.6: unit + integration tests"
      python: 3.6
      env: TOXENV=coverage,complex,spark,doctest,type,check TOX_INSTALL_DIR=.env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - if: type != pull_request
      name: "Python 3.7: unit + integration tests"
      python: 3.7
      env: TOXENV=coverage,complex,spark,doctest,type,check TOX_INSTALL_DIR=.env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# Install JDK8 for PySpark tests
before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk --no-install-recommends
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

install:
  - pip install -U pip setuptools
  - pip install -U tox==3.12.0
  - pip install -U codecov
  - tox --notest

script:
  - tox

after_success:
  - travis_retry codecov

notifications:
  email: 
    recipients:
      secure: "d91inMv9lhRuSDEbT+aRtsrGC0M8VSvloPSoDt1k9k1y1EuduRF3+QuE3kd1T2sz0ARypWvDj1M89Gyfnbdrg/rphmBIIOaLQdjA+zueid6Dpc/6Xxe2nnXCjS+7PL7CkKjHo7iE3XW97Hep7WUEv3A60bD5O9kx0mS9qbKeO5KJTmb7zctVF6s1jz8VGewS+XybDW5ZJ0KDVhvlvunJt+PCDXfGAFxdEuXGF6dOtyAXzZ5h7aRooj06QQPyDO8sDmpbwritR2SXw3OBZi3xO4qZOfLyFWtuo6VvMRTaNa4UNnyP0QGZbHuzZe6/SAqPrU417XwuklVHJQchRFPFrQxcRgNKjOXgD8KM5cuQJJEJIIpppEp0fO902F13Kci9D4Fysd2rCFZWzStTyeyDWYMPtkiNZfWlBVxPUFQcXRAXyz3e7kz6kIVUGnBiuruYrmBb5iuz9dlB8vJfeIml4iAoPnUs1J+NNiirqqRPt629Y3LaISWxcIN/v+oQp+W1XxmwjSf/FhpTDsqG1if7ks4VMjdoFgR76bZ8qBiKBLsdggJPyTljoOs+Tnhe18P2szfNyL47u+/QaZtliR2+bS7dmr9Sd5ol4cfb71xgGJBcJGf3e5OcgAgy3vZdshEGTGHxN+ykRRK4iOcFPjnyLwJmUUEbbn6jpFE0H3N1r2s="
    on_success: change # default: change [change, always, never]
    on_failure: change # default: always
  slack:
    on_success: change # default: change
    on_failure: change # default: always
    on_pull_requests: false
    secure: "Bpa9PkZjJBVd/qYSipW6PU+F3exb4C4lcE02ExpfgCKoKKfcEGMKNMUF8gDFhxKMB0YDuG521me1mpGgHornapZnXXItTZRjs8ryda09/n0Ref0f4sxXjy5wrUte62+BNLmddIZGW4ALUzW1X6XEnsClHz6PfQes88VWc6amoZHGjsb2A8zFzSJa00mQ8D9uUTcVvia9F3rb/dk8ZXeGrx84+EKiVLPjlGiAz/ivVkDgrlY3ufYUKkIgzkzrjJ/FLJbFF0hc6nsAtz0u1D6ps1aryMykS4fLRcITVxlfV3SU1jYy1OKiugf4Ry3TGjMhCUcvYPAvjTngzZWTY0JlhXGmZ0Yc4vEveW5UpyTXUtd6G4/p8QrUF5w8TQeIEjfZh6LK86zxXcIi3dvhJrCEzFh1H3PN1arRA22a0seqbWMg2/OgF3KwRBtpm/mSWdIycKkF8J22rY3PISGSNa78Tx8yspwDMub37yTc6KpO19GNRsgKtlXMmmbRz/pOCHAZFzeiOJNu6kd5w4BAB7ds95Cy3CUXVtVaSLRs2WD0pJInqjgXTXuwpSPo5N5UpV6nxRLSL1cBcXH9zgKrZLdLRUoxaVlFVZc1fv5y/w1frpHRgX6Kx6qeAmSPz8yPatbQXRqUP83m46aV9Hxs4Y7CNDnEanxC1RS3oeprDG+klx4="
