# Only run CI on master, release branches, tags, and PRs
if: tag IS present OR type = pull_request OR ((branch = master OR branch =~ release-*) AND type = push)

language: python

# Cache package wheels
cache: pip

# python3.7 only available on xenial
dist: xenial

env:
  TOXENV=py,check

jobs:
  include:
  - name: "Tests: python3.6"
    python: 3.6
  - name: "Tests: python3.7"
    python: 3.7

install:
- pip install -U pip setuptools
- pip install -U tox==3.12.0
- tox --notest

script:
- tox
