# Only run CI on master, release branches, tags, and PRs
if: tag IS present OR type = pull_request OR ((branch = master OR branch =~ release-*) AND type = push)

# Main dist is Python
language: python

# Cache package wheels
cache: pip

# python3.7 only available on xenial
dist: xenial

env:
  TOXENV=coverage,spark,type,check TOX_INSTALL_DIR=.env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

jobs:
  include:
    - name: "Tests: python3.6"
      python: 3.6
    - name: "Tests: python3.7"
      python: 3.7

# Install JDK8 for PySpark tests
before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk --no-install-recommends
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

install:
  - pip install -U pip setuptools
  - pip install -U tox==3.12.0
  - pip install -U codecov
  - tox --notest

script:
  - tox

after_success:
  - travis_retry codecov
