# Travis CI config for Snorkel, a training data creation and management
# system focused on information extraction

dist: trusty
sudo: false  # to use container-based infra, see: http://docs.travis-ci.com/user/migrating-from-legacy/

language:
  - python
python:
  - "2.7"
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip
    - $HOME/miniconda # to avoid repetitively setting up Miniconda environment
    - parser          # to avoid repetitively downloading CoreNLP

addons:
  apt:
    packages:
    # CoreNLP needs Java 8
    - oracle-java8-installer

# Following trick is necessary to get a binary distribution of numpy, scipy, etc. which takes too long to build every time
# See: http://stackoverflow.com/q/30588634
# See: https://github.com/Theano/Theano/blob/master/.travis.yml (for caching)
# See: http://conda.pydata.org/docs/travis.html
before_install:
  - deactivate  # leaving Travis' virtualenv first since otherwise Jupyter/IPython gets confused with conda inside a virtualenv (See: https://github.com/ipython/ipython/issues/8898)
  - install/conda.sh

  # Make sure Java 8 is used
  - export PATH="/usr/lib/jvm/java-8-oracle/bin:$PATH"
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version

  - source set_env.sh

install:
  - install/python_pkgs.sh
  - install/corenlp.sh

script:
  - source install/miniconda_env.sh
  - ./test.sh

after_success:
  - killall java

after_failure:
  - killall java
