# we only CI the master, release branches, tags and PRs
if: tag IS present OR type = pull_request OR ((branch = master OR branch =~ release-*) AND type = push)

language: python
# cache package wheels (1 cache per python version)
cache: pip
# newer python versions are available only on xenial (while some older only on trusty) Ubuntu distribution
dist: xenial

env:
  TOXENV=py

jobs:
  include:
  - name: "run tests with python 3.5"
    python: 3.5
  - name: "run tests with python 3.6"
    python: 3.6
  - name: "run tests with python 3.7"
    python: 3.7

install:
- pip install -U pip setuptools
- pip install -U tox==3.12.0
- tox --notest

script:
- tox
